# CONDA PYTHON ENVIRONMENT FILE
# 
# USAGE - create
#   conda env create --name naatos_modtools --file environment.yml
# USAGE - update
#   conda env update --name naatos_modtools --file environment.yml --prune

name: naatos_modtools
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10   # 2025-02-25 restriction for Gooey conda package

  # dev tools: vscode/jupyter handiness
  - ipykernel

  # tool user interface
  - gooey=1.0.8.1
  - pyinstaller

  # hardware interaction
  - pyserial
  
  # # std data manip
  # - pandas
  # - numpy
  # - xarray #n-dim-labeled arrays (pandas for n-d arrays)
  # - openpyxl # load excel files from pandas
  # - pytables
  # - scipy # for numerical integration

  # # instrument control
  # - pyvisa      # visa accessing
  # - pyvisa-py   # visa implementation
  
  # # other for specific purposes
  # #- pycparser # for parsing .c files
  # #- pexpect  # for controlling shell commands/programs
  # #- sarge     # for controlling shell commands/programs

  # # for parallel processing from jupyter notebook
  # # - dask

  
  # # image processing
  # # - opencv
  # # - colour-science
  # # - imageio
  # # - scipy
  # # - ffmpeg # for the binary

  # # interactive visuals
  # - panel
  # - holoviews
  # - plotly
  # - hvplot

  # # for notebook-style helper
  # - jupyter_bokeh
  # - nbformat

  # - pip:
  #   # - pure-python-adb             # access adb server
  #   # - colour-checker-detection    # part of colour-science, for segmentation
  #   # - yuvio                       # parse yuv bitstreams as arrays
  #   - easy_scpi                   # instrument control
  #   # - https://github.com/SengerM/TeledyneLeCroyPy
  #   - lecroyscope
  #   - tekinstr

  #   - wmi     # for windows-based automation to help setup the devices

    
